version: '3.8'

volumes:
  mysql-volume:

services:

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    ports:
      - 5173:5173
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql-volume:/var/lib/mysql
      # MySQLの設定ファイルをマウントする例 直接マウントだとMySQLの公式イメージが提供するデフォルトの設定ファイルが上書きされる可能性があるため、chownエラーが出る
      # - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./docker/mysql/conf.d:/etc/mysql/conf.d
      # 違うファイル名でマウントすることで、MySQLの公式イメージが提供するデフォルトの設定ファイルを保持しつつ、カスタム設定を追加できる
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/z-custom.cnf